name: ispy
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  - pip
  - cmocean
  - numpy
  - xarray
  - cartopy
  - networkx
  - shapely
  - matplotlib
  - scipy
  - scikit-learn
  # testing
  - pytest
  - netcdf4
  - requests
  # documentation
  - sphinx
  - sphinx_rtd_theme
  - sphinx-autodoc-typehints
  - sphinx-copybutton
  - pygments
  - nbsphinx
  - nbconvert
  - myst-parser
  - ipython
  # pyicon requirements
  # - pandas
  # - ipywidgets
  # - ipykernel
  # - jupytext
  # - nbconvert
  # - healpy
  # - dask[complete]
  # - intake
  # - zarr
  # - intake-xarray
  # - intake-esm
  # - ipdb
  # extras
  - flox
  - numba
  - numbagg
  - bottleneck
  - dask-mpi
  - distributed
  - requests
  - aiohttp
  - sparse
  - h5netcdf
  # - pip:
    # - pyicon-diagnostics @ git+https://gitlab.dkrz.de/m300602/pyicon.git